T_max: 500
checkpoint_path:
epochs: 50
image_size: 384
learning_rate: 0.0001
min_lr: 1.0e-06
model_name: tf_efficientnet_b0_ns
n_accumulate: 1
scheduler: CosineAnnealingLR
weight_decay: 1.0e-06
classes: 4
train_batch_size: 16
valid_batch_size: 32